---
- name: reload networking
  command: "ifreload -a"

- name: restart frr
  service:
    name: frr
    state: restarted
  async: 60

- name: reload frr
  service:
    name: frr
    state: reloaded
  async: 60
