---
- hosts: oob
  become: true
  roles:
  - oob-mgmt-server
  - netq-agent
  environment: "{{ proxy_env }}"

- hosts: netq-ts
  become: true
  roles:
  - app-netq
  - app-grafana
  - app-netbox
  environment: "{{ proxy_env }}"

- hosts: spines,superspine
  become: true
  roles:
  - setup-switch
  - switch-spine
  environment: "{{ proxy_env }}"

- hosts: leafs,edge,router
  become: true 
  roles:
  - setup-switch
  - switch-leaf
  environment: "{{ proxy_env }}"

- hosts: servers-rack1,servers-rack2,servers-rack3
  become: true 
  roles:
  - setup-server
  - server-multitenant
  environment: "{{ proxy_env }}"

- hosts: servers-rack1,servers-rack2,servers-rack3
  become: true 
  roles:
  - server-evpn
  tasks:
  - name: reboot
    reboot:
      reboot_timeout: 1200
      test_command: mount
  environment: "{{ proxy_env }}"
