- hosts: servers-rack1,servers-rack3 
  become: yes
  tasks:
    - name: kill iperf 
      command: killall -q iperf3
      ignore_errors: true

    - name: Start Iperf daemon
      command: ip vrf exec "{{ item.app }}" iperf3 -p "{{ item.port }}" -s -D
      loop:
        - { app: 'app2', port: '40001'} 
        - { app: 'app2', port: '50001'} 
        - { app: 'app2', port: '40002'} 
        - { app: 'app2', port: '50002'} 
        - { app: 'app2', port: '40003'} 
        - { app: 'app2', port: '50003'} 
        - { app: 'app2', port: '40004'} 
        - { app: 'app2', port: '50004'} 
        - { app: 'app2', port: '40005'} 
        - { app: 'app2', port: '50005'} 
        - { app: 'app2', port: '40006'} 
        - { app: 'app2', port: '50006'} 
        - { app: 'app4', port: '40001'} 
        - { app: 'app4', port: '50001'} 
        - { app: 'app4', port: '40002'} 
        - { app: 'app4', port: '50002'} 
        - { app: 'app4', port: '40003'} 
        - { app: 'app4', port: '50003'} 
        - { app: 'app4', port: '40004'} 
        - { app: 'app4', port: '50004'} 
        - { app: 'app4', port: '40005'} 
        - { app: 'app4', port: '50005'} 
        - { app: 'app4', port: '40006'} 
        - { app: 'app4', port: '50006'} 
        - { app: 'app6', port: '40001'} 
        - { app: 'app6', port: '50001'} 
        - { app: 'app6', port: '40002'} 
        - { app: 'app6', port: '50002'} 
        - { app: 'app6', port: '40003'} 
        - { app: 'app6', port: '50003'} 
        - { app: 'app6', port: '40004'} 
        - { app: 'app6', port: '50004'} 
        - { app: 'app6', port: '40005'} 
        - { app: 'app6', port: '50005'} 
        - { app: 'app6', port: '40006'} 
        - { app: 'app6', port: '50006'} 

- hosts: servers-rack2 
  become: yes
  tasks:
    - name: kill iperf 
      command: killall -q iperf3
      ignore_errors: true

    - name: Start Iperf daemon
      command: ip netns exec "{{ item.app }}" iperf3 -p "{{ item.port }}" -s -D
      loop:
        - { app: 'vm11', port: '40001'} 
        - { app: 'vm11', port: '50001'} 
        - { app: 'vm11', port: '40002'} 
        - { app: 'vm11', port: '50002'} 
        - { app: 'vm11', port: '40003'} 
        - { app: 'vm11', port: '50003'} 
        - { app: 'vm11', port: '40004'} 
        - { app: 'vm11', port: '50004'} 
        - { app: 'vm11', port: '40005'} 
        - { app: 'vm11', port: '50005'} 
        - { app: 'vm11', port: '40006'} 
        - { app: 'vm11', port: '50006'} 
        - { app: 'vm13', port: '40001'} 
        - { app: 'vm13', port: '50001'} 
        - { app: 'vm13', port: '40002'} 
        - { app: 'vm13', port: '50002'} 
        - { app: 'vm13', port: '40003'} 
        - { app: 'vm13', port: '50003'} 
        - { app: 'vm13', port: '40004'} 
        - { app: 'vm13', port: '50004'} 
        - { app: 'vm13', port: '40005'} 
        - { app: 'vm13', port: '50005'} 
        - { app: 'vm13', port: '40006'} 
        - { app: 'vm13', port: '50006'} 
        - { app: 'vm15', port: '40001'} 
        - { app: 'vm15', port: '50001'} 
        - { app: 'vm15', port: '40002'} 
        - { app: 'vm15', port: '50002'} 
        - { app: 'vm15', port: '40003'} 
        - { app: 'vm15', port: '50003'} 
        - { app: 'vm15', port: '40004'} 
        - { app: 'vm15', port: '50004'} 
        - { app: 'vm15', port: '40005'} 
        - { app: 'vm15', port: '50005'} 
        - { app: 'vm15', port: '40006'} 
        - { app: 'vm15', port: '50006'} 


- hosts: servers-rack1,servers-rack3 
  become: yes
  tasks:
    - name: IPv4 Iperf traffic 
      command: screen -dm ip vrf exec "{{ item.app }}" iperf3 -p 400{{ inventory_hostname[-2:] }} -c 192.168."{{ item.prefix }}"."{{ item.destination }}" -P 3 -t 420 -b 1k -Z -M 1350 -w 8192
      loop:
        - { app: 'app1', prefix: '11', destination: '11'} 
        - { app: 'app1', prefix: '11', destination: '12'} 
        - { app: 'app1', prefix: '11', destination: '30'} 
        - { app: 'app1', prefix: '11', destination: '40'} 
        - { app: 'app1', prefix: '11', destination: '15'} 
        - { app: 'app1', prefix: '11', destination: '16'} 
        - { app: 'app3', prefix: '13', destination: '11'} 
        - { app: 'app3', prefix: '13', destination: '12'} 
        - { app: 'app3', prefix: '13', destination: '30'} 
        - { app: 'app3', prefix: '13', destination: '40'} 
        - { app: 'app3', prefix: '13', destination: '15'} 
        - { app: 'app3', prefix: '13', destination: '16'} 
        - { app: 'app5', prefix: '15', destination: '11'} 
        - { app: 'app5', prefix: '15', destination: '12'} 
        - { app: 'app5', prefix: '15', destination: '30'} 
        - { app: 'app5', prefix: '15', destination: '40'} 
        - { app: 'app5', prefix: '15', destination: '15'} 
        - { app: 'app5', prefix: '15', destination: '16'} 

#    - name: IPv6 Iperf traffic 
#      command: screen -dm ip vrf exec "{{ item.app }}" iperf3 -p 500{{ inventory_hostname[-2:] }} -c fc00:"{{ item.prefix }}"::"{{ item.destination }}" -P 3 -t 420 -b 1k -Z -M 1350 -w 8192
#      loop:
#        - { app: 'app1', prefix: '11', destination: '11'} 
#        - { app: 'app1', prefix: '11', destination: '12'} 
#        - { app: 'app1', prefix: '11', destination: '30'} 
#        - { app: 'app1', prefix: '11', destination: '40'} 
#        - { app: 'app1', prefix: '11', destination: '15'} 
#        - { app: 'app1', prefix: '11', destination: '16'} 
#        - { app: 'app3', prefix: '13', destination: '11'} 
#        - { app: 'app3', prefix: '13', destination: '12'} 
#        - { app: 'app3', prefix: '13', destination: '30'} 
#        - { app: 'app3', prefix: '13', destination: '40'} 
#        - { app: 'app3', prefix: '13', destination: '15'} 
#        - { app: 'app3', prefix: '13', destination: '16'} 

- hosts: servers-rack2 
  become: yes
  tasks:
    - name: IPv4 Iperf traffic 
      command: screen -dm ip netns exec "{{ item.app }}" iperf3 -p 400{{ inventory_hostname[-2:] }} -c 192.168."{{ item.prefix }}"."{{ item.destination }}" -P 3 -t 420 -b 1k -Z -M 1350 -w 8192
      loop:
        - { app: 'vm10', prefix: '11', destination: '11'} 
        - { app: 'vm10', prefix: '11', destination: '12'} 
        - { app: 'vm10', prefix: '11', destination: '30'} 
        - { app: 'vm10', prefix: '11', destination: '40'} 
        - { app: 'vm10', prefix: '11', destination: '15'} 
        - { app: 'vm10', prefix: '11', destination: '16'} 
        - { app: 'vm12', prefix: '13', destination: '11'} 
        - { app: 'vm12', prefix: '13', destination: '12'} 
        - { app: 'vm12', prefix: '13', destination: '30'} 
        - { app: 'vm12', prefix: '13', destination: '40'} 
        - { app: 'vm12', prefix: '13', destination: '15'} 
        - { app: 'vm12', prefix: '13', destination: '16'} 
        - { app: 'vm14', prefix: '15', destination: '11'} 
        - { app: 'vm14', prefix: '15', destination: '12'} 
        - { app: 'vm14', prefix: '15', destination: '30'} 
        - { app: 'vm14', prefix: '15', destination: '40'} 
        - { app: 'vm14', prefix: '15', destination: '15'} 
        - { app: 'vm14', prefix: '15', destination: '16'} 

#    - name: IPv6 Iperf traffic 
#      command: screen -dm ip netns exec "{{ item.app }}" iperf3 -p 500{{ inventory_hostname[-2:] }} -c fc00:"{{ item.prefix }}"::"{{ item.destination }}" -P 3 -t 420 -b 1k -Z -M 1350 -w 8192 
#      loop:
#        - { app: 'vm10', prefix: '11', destination: '11'} 
#        - { app: 'vm10', prefix: '11', destination: '12'} 
#        - { app: 'vm10', prefix: '11', destination: '30'} 
#        - { app: 'vm10', prefix: '11', destination: '40'} 
#        - { app: 'vm10', prefix: '11', destination: '15'} 
#        - { app: 'vm10', prefix: '11', destination: '16'} 
#        - { app: 'vm12', prefix: '13', destination: '11'} 
#        - { app: 'vm12', prefix: '13', destination: '12'} 
#        - { app: 'vm12', prefix: '13', destination: '30'} 
#        - { app: 'vm12', prefix: '13', destination: '40'} 
#        - { app: 'vm12', prefix: '13', destination: '15'} 
#        - { app: 'vm12', prefix: '13', destination: '16'} 
