---
- name: Add Cumulus Apt Key
  apt_key:
    url: "https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey"
    state: present

- name: Add Cumulus Repo
  apt_repository:
    repo: "deb https://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-{{ netq.version }}"
    state: present
    update_cache: no

- name: Install Python Depandancy
  command: "{{ item }}"
  loop:
    - 'pip3 install PyYAML'
    - 'pip3 install pynetbox==3.4.7'

- name: Install additional host packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - iperf3
    - lldpd
    - traceroute
    - iproute
    - iproute2
    - netq-agent
    - python3-pip
