---
- name: Add Cumulus Apt Key
  apt_key:
    url: "https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey"
    state: present

- name: Add Cumulus {{ netq.version }} Repo
  apt_repository:
    repo: "deb https://apps3.cumulusnetworks.com/repos/deb xenial netq-{{ netq.version }}"
    state: present
    update_cache: no

- name: Install Python Depndency
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  loop:
    - PyYAML
    - pynetbox==3.4.7

- name: Install Host Depndency
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - iperf3
    - lldpd
    - traceroute
    - iproute
    - iproute2
    - netq-agent
    - netq-apps
    - python3-pip

- name: Start NetQ
  command: "{{ item }}"
  loop:
    - systemctl enable netq-agent
    - systemctl start netq-agent
