---
- name: Install Python Depndency
  pip:
    name: "{{ item }}"
    executable: /usr/bin/pip3
  loop:
    - PyYAML
    - pynetbox==3.4.7

- name: Install Host Depndency
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    - iperf3
    - lldpd
    - traceroute
    - iproute
    - iproute2
    - python3-pip
